<?php

namespace WeDevBr\Celcoin\Enums;

enum AmountDiscountModalityTypeEnum: string
{
    case FIXED_VALUE_UNTIL_THE_DATES_INFORMED = 'FIXED_VALUE_UNTIL_THE_DATES_INFORMED';
    case PERCENTAGE_DATE_REPORTED = 'PERCENTAGE_DATE_REPORTED';
    case AMOUNT_PER_CALENDAR_DAY_ADVANCE = 'AMOUNT_PER_CALENDAR_DAY_ADVANCE';
    case AMOUNT_ADVANCE_BUSINESS_DAY = 'AMOUNT_ADVANCE_BUSINESS_DAY';
    case PERCENTAGE_ADVANCE_CURRENT_DAY = 'PERCENTAGE_ADVANCE_CURRENT_DAY';
    case PERCENTAGE_ADVANCE_BUSINESS_DAY = 'PERCENTAGE_ADVANCE_BUSINESS_DAY';
}
