<?php

namespace WeDevBr\Celcoin\Types\BAAS;

use WeDevBr\Celcoin\Types\Data;

class GetPaymentStatusRequest extends Data
{
    public ?string $clientRequestId = null;

    public ?string $id = null;
    private ?string $ClientRequestId = null;
    private ?string $Id = null;

    public function __construct(array $data = [])
    {
        parent::__construct($data);
    }

    public function toArray(): array
    {
        $this->Id = $this?->id;
        $this->ClientRequestId = $this?->clientRequestId;
        return collect(parent::toArray())->only(['Id', 'ClientRequestId'])->toArray(); // TODO: Change the autogenerated stub
    }
}